users/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

viapp/urls.py
# адреса для страниц приложения viapp

from django.urls import path

from . import views

app_name = 'viapp'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница альбомов
    path('albums/', views.albums, name='albums'),
    # Страница альбома
    path('albums/<int:album_id>/', views.album, name='album'),
    # Страница фотографии
    path('album/<int:photo_id>/', views.photo, name='photo'),
    # Страница добавления альбома (для администратора)
    path('add_album/', views.add_album, name='add_album'),
    # Страница добавления фотографии (для администратора)
    path('add_photo/<int:album_id>/', views.add_photo, name='add_photo'),
    # Страница скачивания фотографий
    path('download_photo/<int:photo_id>/', views.download_photo, name = 'download_photo'),
    # Страница удаления фотографии (для администратора)
    path('delete_photo/<int:photo_id>/', views.delete_photo, name = 'delete_photo'),
    # Страница для скачивания альбома целиком
    path('download_album/<int:album_id>', views.download_album, name = 'download_album'),
    # Страница удаления альбома (для администратора)
    path('delete_album/<int:album_id>/', views.delete_album, name = 'delete_album'),
    # Страница удаления нескольких выбранных фотографий в альбоме (для администратора)
    path('delete_selected_photos/<int:album_id>/', views.delete_selected_photos, name = 'delete_selected_photos'),
    # Страница выбора обложки альбома (для администратора)
    path('select_cover/<int:album_id>/<int:photo_id>/', views.select_cover, name = 'select_cover'),
    # Страница перемещения расположения фотографии (для администратора)
    path('update_photo_order/', views.update_photo_order, name = 'update_photo_order'),
    # Страница для того, чтобы делиться правом просмотра альбома
    path('albums/<int:album_id>/share/', views.share_album, name='share_album'),
]

vitochka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name = 'index'),
    path('', include('viapp.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viapp/models.py
from django.db import models
from django.conf import settings


class Album(models.Model):
	# Альбом для просмотра фотографий
	title = models.CharField(max_length=100, verbose_name="Название альбома")
	description = models.TextField(blank=True, default="Без описания", verbose_name="Описание альбома")
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
	shared_with = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="shared_albums",
	                                     verbose_name="Доступ для пользователей")
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="albums")
	cover = models.ForeignKey(
		'Photo',
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		verbose_name="Обложка альбома",
		related_name="cover_for_albums"
	)

	def __str__(self):
		return self.title

	class Meta():
		verbose_name = "Альбом"
		verbose_name_plural = "Альбомы"

class Photo(models.Model):
	title = models.CharField(max_length=100, null=True, blank=True, verbose_name="Название фотографии")
	description = models.TextField(blank=True, verbose_name="Описание фотографии")
	album = models.ForeignKey(Album, related_name="photos", on_delete=models.CASCADE, verbose_name="Альбом")
	image = models.ImageField(upload_to='photos/', verbose_name=" Фотография")
	caption = models.CharField(max_length=255, blank=True, null=True, verbose_name="Подпись")
	uploaded_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки")
	order = models.PositiveIntegerField(default=0, verbose_name="Порядок")

	def __str__(self):
		return f"{self.title} - альбом: {self.album.title}"

	class Meta:
		verbose_name = "Фотография"
		verbose_name_plural = "Фотографии"
		ordering = ['order'] # сортировка по умолчанию

viapp/forms.py
from django import forms

from .models import Album, Photo


class AlbumForm(forms.ModelForm):
	class Meta:
		model = Album
		fields = ['title', 'description']

class MultipleFileInput(forms.ClearableFileInput):
	allow_multiple_selected = True

class MultipleFileField(forms.FileField):
	def __init__(self, *args, **kwargs):
		kwargs.setdefault("widget", MultipleFileInput())
		super().__init__(*args, **kwargs)

	def clean(self, data, initial = None):
		return(super().clean(file, initial) for file in data)

class PhotoForm(forms.ModelForm):
	images = MultipleFileField(label = "Фотографии")

	class Meta:
		model = Photo
		fields = []

viapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseForbidden
from django.db.models import Q
from django.http import FileResponse, HttpResponse, JsonResponse
from django.contrib.auth import get_user_model

import zipfile
import os
import json

from io import BytesIO

from .models import Album, Photo
from .forms import AlbumForm, PhotoForm

# декоратор - проверка того, является ли пользователь администратором
def admin_required(view_func):
	"""Декоратор для проверки прав суперпользователя."""
	def wrapper(request, *args, **kwargs):
		if not request.user.is_superuser:
			raise PermissionDenied("Доступ запрещён.")
		return view_func(request, *args, **kwargs)
	return wrapper

# Create your views here.
def index(request):
	"""Домашняя страница приложения"""
	return render(request, 'viapp/index.html')

@login_required()
def albums(request):
	# выводит список альбомов
	if request.user.is_superuser:
		albums = Album.objects.all().order_by('created_at')
	else:
		albums = Album.objects.filter(
			Q(owner=request.user) | Q(shared_with=request.user)
		).distinct().order_by('created_at')
	context = {'albums': albums}
	return render(request, 'viapp/albums.html', context)

@login_required()
def album(request, album_id):
	# страница альбома. Выводит альбом и фотографии в нем содержащиеся
	album = get_object_or_404(Album, id=album_id)
	# Проверка того, что альбом принадлежит текущему пользователю.
	if not (
			request.user.is_superuser or
			album.owner == request.user or
			request.user in album.shared_with.all()
	):
		raise PermissionDenied()
	photo = album.photos.order_by('-uploaded_at')
	context = {'album':album, 'photo':photo}
	return render(request, 'viapp/album.html', context)

@login_required()
def photo(request, photo_id):
	#страница фотографии
	photo = get_object_or_404(Photo, id=photo_id)
	album = photo.album

	# Все фото в альбоме отсортированные по ID
	all_photos = Photo.objects.filter(album=album).order_by('order')

	# Находим текущий индекс фото в списке
	photo_list = list(all_photos)
	current_index = photo_list.index(photo)

	# Следующее фото
	next_photo = photo_list[current_index+1] if current_index + 1 < len(photo_list) else None

	# Предыдущее фото
	prev_photo = photo_list[current_index-1] if current_index - 1 >= 0 else None

	# Проверка того, что фото принадлежит текущему пользователю.
	if not (
			request.user.is_superuser
			or photo.album.owner != request.user
			or request.user in album.shared_with.all()
	):
		raise PermissionDenied()
	context = {'photo':photo,
				'next_photo': next_photo,
				'prev_photo': prev_photo,
				}
	return render(request, 'viapp/photo.html', context)

# функция добавления альбома
@login_required()
@admin_required
def add_album(request):
	# Страница добавления альбома
	if request.method != 'POST':
		form = AlbumForm()
	else:
		form = AlbumForm(data = request.POST)
		if form.is_valid():
			add_album = form.save(commit=False)
			add_album.owner = request.user
			add_album.save()
			return redirect ('viapp:albums')
	context = {'form' : form}
	return render(request, 'viapp/add_album.html', context)

# функция добавления фотографий
@login_required()
@admin_required
def add_photo(request, album_id):
	album = Album.objects.get(id=album_id)

	if request.method != 'POST':
		form = PhotoForm(initial={'album': album})
	else:
		form = PhotoForm(request.POST, request.FILES)
		if form.is_valid():
			images = request.FILES.getlist('images')

			for image in images:
				Photo.objects.create(
					album = album,
					title = form.cleaned_data.get('title', ''),
					description = form.cleaned_data.get('description', ''),
					image = image
				)
			return redirect('viapp:album', album_id = album.id)

	context = {'form' : form, 'album': album}
	return render(request, 'viapp/add_photo.html', context)

# Функция загрузки фото
@login_required()
def download_photo(request, photo_id):
	photo = Photo.objects.get(id = photo_id)
	if not request.user.is_superuser and photo.album.owner != request.user:
		raise PermissionDenied()
	else:
		file = open(photo.image.path, 'rb')
		response = FileResponse(file)

	# Имя файла для скачивания
	response['Content-Disposition'] = f'attachment; filename = "{photo.image.name}"'
	return response

# Функция удаления фото
@login_required()
def delete_photo(request, photo_id):
	photo = Photo.objects.get(id=photo_id)
	if not request.user.is_superuser and photo.album.owner != request.user:
		raise PermissionDenied()
	else:
		photo.delete()
		return redirect('viapp:album', album_id=photo.album.id)

# Функция загрузки альбома
def download_album(request, album_id):
	album = Album.objects.get(id = album_id)
	zip_buffer = BytesIO()
	with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
		for photo in album.photos.all():
			photo_path = photo.image.path
			if os.path.exists(photo_path):
				zip_file.write(photo_path, os.path.basename(photo_path))

	zip_buffer.seek(0)
	response = HttpResponse(zip_buffer, content_type='application/zip')
	response['Content-Disposition'] = f'attachment; filename = "{album.title}.zip"'
	return response

# Функция удаления альбома
def delete_album(request, album_id):
	album = Album.objects.get(id=album_id)
	if not request.user.is_superuser and photo.album.owner != request.user:
		raise PermissionDenied()
	else:
		album.delete()
		return redirect('viapp:albums')

# Функция удаления выбранных фото
def delete_selected_photos(request, album_id):
	album = Album.objects.get(id=album_id)

	# Проверка прав
	if not request.user.is_superuser and album.owner != request.user:
		raise PermissionDenied("У вас нет прав на удаление фотографий")

	if request.method == 'POST':
		photo_ids = request.POST.getlist('photo_ids')
		if photo_ids:
			# Удаляем только фотографии из текущего альбома
			Photo.objects.filter(
				id__in=photo_ids,
				album=album
			).delete()

		return redirect('viapp:album', album_id=album.id)

	return redirect('viapp:album', album_id=album.id)

# Функция выбора обложки альбома
@login_required
@admin_required
def select_cover(request, album_id, photo_id):
	album = Album.objects.get(id=album_id)
	photo = Photo.objects.get(id=photo_id)

	album.cover = photo
	album.save()
	return redirect('viapp:album', album_id=album.id)

# Функция обновления порядка фотографий
@login_required
@admin_required
def update_photo_order(request):
	if request.method == 'POST':
		try:
			data = json.loads(request.body)
			for item in data:
				photo = Photo.objects.get(id=item['id'])
				photo.order = item['order']
				photo.save()
			return JsonResponse({'status': 'success'})
		except Exception as e:
			return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
	return JsonResponse({'status': 'error'}, status=405)

def user_albums(request):
	user = request.user
	if not user.is_authenticated:
		return HttpResponseForbidden("Необходимо войти в систему")

	albums = Album.objects.filter(
		Q(owner=user) | Q(shared_with=user)
	).distinct()

	return render(request, "albums.html", {"albums": albums})

def album_photos(request, album_id):
	user = request.user
	album = get_object_or_404(Album, id=album_id)

	# Проверка доступа
	if user != album.owner and user not in album.shared_with.all():
		return HttpResponseForbidden("У вас нет доступа к этому альбому")

	photos = album.photos.all()
	return render(request, "photos.html", {"album": album, "photos": photos})

@login_required
def share_album(request, album_id):
	album = get_object_or_404(Album, id=album_id)

	# Только владелец или суперюзер может делиться
	if not request.user.is_superuser and album.owner != request.user:
		return HttpResponseForbidden("У вас нет прав делиться этим альбомом")

	if request.method == "POST":
		user_ids = request.POST.getlist("users")
		User = get_user_model()
		users = User.objects.filter(id__in=user_ids)
		album.shared_with.set(users)
		return redirect("viapp:album", album_id=album.id)

	# Используем кастомного пользователя
	User = get_user_model()
	users = User.objects.exclude(id=request.user.id)
	return render(request, "viapp/share_album.html", {"album": album, "users": users})

templates/viapp/add_album.html
{% extends 'viapp/base.html' %}

{% block title %}Добавить альбом{% endblock %}

{% block content %}
<div class="container-fluid ms-1 mt-1">
 <div class="row justify-content-start">
 <div class="col-md-8">
 <h2 class="mb-4"><span class="badge bg-dark">Добавить альбом</span></h2>
 <form action="{% url 'viapp:add_album' %}" method="post" class="needs-validation" novalidate>
 {% csrf_token %}
 
 <div class="form-group">
 {{ form.as_p|safe }}
 </div>
 
 <button type="submit" class="btn btn-primary">Сохранить</button>
 </form>
 </div>
 </div>
</div>
{% endblock %}

templates/viapp/add_photo.html
{% extends 'viapp/base.html' %}

{% block title %}Добавить фотографию{% endblock %}

{% block content %}
<div class="container mt-1 ms-1">
    <div class="row justify-content-start">
        <div class="col-md-8">
            <h2 class="mb-4">Добавить фотографии</h2>
            <form action="{% url 'viapp:add_photo' album.id %}" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                {% csrf_token %}
                
                <!-- Скрытое поле для альбома -->
                <input type="hidden" name="album" value="{{ album.id }}">
                
                <div class="form-group">
                    {{ form.as_p|safe }}
                </div>
                
                <button type="submit" class="btn btn-primary">Загрузить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/viapp/album.html
{% extends 'viapp/base.html' %}


{% block title %}{{ album.title }}{% endblock %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

<style>
  /* Устанавливаем требования к отображению картинок */

  body {
    padding-top: 270px; /* 50px для первой панели + 50px для второй */
    }


  .photo-card {
    position: relative;
    width: 100%;
    aspect-ratio: 1 / 1; /* квадратная карточка, адаптивно */
    overflow: hidden;
    background: transparent; /* фон, если фото не полностью заполнит */
    border: none; /* убираем рамку */
    transition: transform 0.2s;
    cursor: {% if request.user.is_superuser %}grab{% else %}default{% endif %};
    /* Добавляем вертикальное выравнивание */
    display: flex;
    align-items: center;
    justify-content: center;
}
  }
  
  .photo-card:active { cursor: grabbing; }
  
  .photo-card img{
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
  }


  .photo-card-link {
      display: block;
      text-decoration: none;
      color: inherit;
  }


  /* фиксация сверху навигационной панели */
  .second-nav {
    position: fixed;
    top: 55px; /* Высота первой панели */
    width: 100%;
    z-index: 1029; /* На 1 меньше, чем у первой панели */
  }

  /* 55px отступ для контейнера содержимого страницы */
  .main-container {
  top: 200px
  }
</style>

<!-- Верхняя панель -->
<nav class="navbar fixed-top navbar-light bg-light second-nav border-bottom border-3 border-dark ">
  <div class="container-fluid main-container">
    <div class="mx-5 w-100 d-flex justify-content-between align-items-center">
      <div class="col-5">
        <div class="row d-flex justify-content-start align-items-stretch">
          <div class = "col-3 d-flex align-items-center">

            <!-- Ссылка на все альбомы -->
            <a href="{% url 'viapp:albums' %}" class="btn btn-outline-secondary">
              ← Все альбомы
            </a>
          </div>
          {% if request.user.is_superuser or album.owner == request.user %}
          <div class = "col-5 d-flex align-items-center">

            <!-- Скачать альбом -->
            <a href="{% url 'viapp:download_album' album.id %}" class="btn btn-outline-secondary">
              <i class="bi bi-download"></i> Скачать альбом (ZIP)
            </a>
          </div>
          {% endif %}
        </div>

        <!-- Наименование Альбома -->
        <h1 class="display-5 fw-bold">{{ album.title }}</h1>
        <p class="text-muted small">Создан: {{ album.created_at|date:"d.m.Y" }}</p>
      </div>

      <!-- Блок только для администратора -->
      {% if request.user.is_superuser %}

      <!-- Группа кнопок (admin_only) -->
      <div class="btn-group d-flex flex-column justify-content-between align-items-end ">

          <!-- Загрузить фотографии -->
          <a href="{% url 'viapp:add_photo' album.id %}" class="btn btn-outline-primary rounded-2 my-2">
            <i class="bi bi-plus-lg"></i> Загрузить фотографии в альбом
          </a>

          <!-- Удалить выбранные фотографии -->

          <button type="button" class="btn btn-outline-warning rounded-2 my-2" onclick="deleteSelected()">
            <i class="bi bi-trash"></i> Удалить выбранные фотографии
          </button>

          <!-- Удалить альбом целиком -->
          <a href="{% url 'viapp:delete_album' album.id %}" class="btn btn-outline-danger rounded-2 my-2"
               onclick="return confirm('Удалить альбом?')">
            <i class="bi bi-trash"></i> Удалить альбом целиком
          </a>
      </div>
      {% endif %}
    </div>
  </div>
</nav>

<!-- Все содержимое страницы -->
<div class="container-fluid main-container">

<!-- Список фотографий в альбоме -->
<form id="photoForm" method="post" action="{% url 'viapp:delete_selected_photos' album.id %}">
  {% csrf_token %}
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-6 row-cols-xxl-6 g-4 mx-2" 
       id="photo-list">

    {% for photo in album.photos.all %}

    <div class="photo-item " data-id="{{ photo.id }}"
         draggable="{% if request.user.is_superuser %}true{% else %}false{% endif %}">
      
      <!-- Карточка фотографий -->
      <a href="{% url 'viapp:photo' photo.id %}" class="photo-card-link">
        <div class='photo-card card '>

          <!-- Чекбокс для выбора фотографии только для админа -->
          {% if request.user.is_superuser %}
          <div class="position-absolute bottom-0 end-0 mx-3 my-2 ">
            <input class="form-check-input border border-1 border-dark" type="checkbox" name="photo_ids" value="{{ photo.id }}">
          </div>

          <!-- Кнопка сделать фото обложкой альбома -->
          <div class="position-absolute bottom-0 start-0 mx-3 my-2">
            <form action="{% url 'viapp:select_cover' album.id photo.id %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" 
                      class="btn btn-outline-dark btn-sm w-100"
                      data-bs-toggle="tooltip" 
                      title="Сделать обложкой"
                      data-bs-placement="top">
                <i class="bi bi-star"></i>
              </button>
            </form>
          </div>
          {% endif %}
          <!-- Отображение фотографий с ссылкой в изображении -->
            <img src="{{ photo.image.url }}" class ="img-fluid object-fit-scale border rounded" alt="{{ photo.title }}"> 
        </div>
      </a>
    </div>
    {% endfor %}
  </div>

</form>

<!-- Выбрать все фотографии в альбоме -->
{% if request.user.is_superuser %}
<div class = "float-end my-5 me-5">
  <div style="margin-bottom: 10px;">
    <input type="checkbox" id="select-all">
    <label for="select-all">
      <p class="fs-4"> Выбрать все фотографии </p>
  </label>
  </div>
</div>
{% endif %}

</div>

<!-- право поделиться просмотром альбома -->
{% if request.user == album.owner or request.user.is_superuser %}
  <a href="{% url 'viapp:share_album' album.id %}" class="btn btn-outline-primary rounded-2 my-4">
    <i class="bi bi-plus-lg"></i> Поделится альбомом с другими пользователями
  </a>

{% endif %}

<!-- список тех кому доступен альбом -->
{% if request.user.is_superuser or request.user == album.owner %}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <h5> Доступ к альбому предоставлен пользователям: </h5>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        {% if album.shared_with.all %}
        <div class ="container-fluid mt-3">
          <table class="table">
            <thead>
            <tr>
              <th scope="col">№</th>
              <th scope="col">User_name</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for user in album.shared_with.all %}
                <tr>
                  <th scope="row"> {{ forloop.counter }} </th>
                  <td> {{ user.username }} </td>
                </tr>
            {% empty %}
                <li>Пока никому не предоставлен доступ</li>
            {% endfor %}
            </tbody>
          </table>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endif %}


<script>
  // Выбор всех чекбоксов
  document.getElementById('select-all')?.addEventListener('click', function() {
    document.querySelectorAll('input[name="photo_ids"]').forEach(checkbox => {
      checkbox.checked = this.checked;
    });
  });

  // Подтверждение удаления
  function deleteSelected() {
    if (confirm('Удалить выбранные фотографии?')) {
      document.getElementById('photoForm').submit();
    }
  }


  // Drag-and-drop для админа
  {% if request.user.is_superuser %}
  document.addEventListener('DOMContentLoaded', () => {
    const photoList = document.getElementById('photo-list');
    let draggedItem = null;

    photoList.addEventListener('dragstart', (e) => {
      const item = e.target.closest('.photo-item');
      if (item) {
        draggedItem = item;
        item.style.opacity = '0.5';
        e.dataTransfer.effectAllowed = 'move';
        e.dataTransfer.setData('text/plain', item.dataset.id);
      }
    });

    photoList.addEventListener('dragover', (e) => {
      e.preventDefault();
      const afterElement = getDragAfterElement(photoList, e.clientY);
      if (afterElement) {
        photoList.insertBefore(draggedItem, afterElement);
      } else {
        photoList.appendChild(draggedItem);
      }
    });

    photoList.addEventListener('dragend', async () => {
      draggedItem.style.opacity = '1';
      const photos = Array.from(photoList.children);
      const orderData = photos.map((item, index) => ({
        id: parseInt(item.dataset.id),
        order: index + 1
      }));

      try {
        const response = await fetch("{% url 'viapp:update_photo_order' %}", {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
          },
          body: JSON.stringify(orderData)
        });
        if (response.ok) location.reload();
      } catch (error) {
        console.error('Ошибка:', error);
      }
    });

    function getDragAfterElement(container, y) {
      const elements = [...container.querySelectorAll('.photo-item:not(.dragging)')];
      return elements.reduce((closest, child) => {
        const box = child.getBoundingClientRect();
        const offset = y - box.top - box.height / 2;
        if (offset < 0 && offset > closest.offset) {
          return { element: child, offset };
        } else {
          return closest;
        }
      }, { element: null, offset: -Infinity }).element;
    }
  });
  {% endif %}
</script>


{% endblock %}

templates/viapp/photo.html
{% extends 'viapp/base.html' %}

{% block title %}{{ photo.title }}{% endblock %}

{% block content %}

<style>

.container-window {
    justify-content: center;
    align-items: center;
    width: 100%;

    overflow: hidden;
    object-fit: contain; /* сохраняет пропорции и вписывает целиком */

.image-container {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    max-height: 60vh;
    overflow: hidden;
}

.photo-img {
    max-width: 100%;
    max-height: 60vh; /* ← ключевое ограничение по высоте */
    height: auto;
    width: auto;
    object-fit: contain; /* сохраняет пропорции и вписывает целиком */
}
</style>



<div class="container-window mt-4 ">
    <div class="row justify-content-center justify-content-center">
        <div class="col-md-8 d-flex justify-content-center ">
            <div class="card">

                    <div class="mb-3">
                        <div class="image-container">
                            <img src="{{ photo.image.url }}" alt="{{ photo.title }}" class="photo-img">
                        </div>
                    </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">
                        <!-- Скачать фото -->
                        <a href="{% url 'viapp:download_photo' photo.id %}" class="btn btn-primary">
                            Скачать фото
                        </a>

                        <!-- Удалить фото -->
                        {% if request.user.is_superuser %}
                            <a href="{% url 'viapp:delete_photo' photo.id %}" class="btn btn-danger"
                               onclick="return confirm('Удалить фото? Это действие нельзя отменить!')">
                                Удалить фото
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Навигация -->
    <div class="row justify-content-center mt-4 ">
        <div class="col-md-8 ">
            <div class="btn-group btn-group-lg w-100 ">
                {% if prev_photo %}
                    <a href="{% url 'viapp:photo' prev_photo.id %}" class="btn btn-outline-primary mx-1 rounded-4">
                        ← Предыдущая
                    </a>
                {% endif %}

                {% if next_photo %}
                    <a href="{% url 'viapp:photo' next_photo.id %}" class="btn btn-outline-primary mx-1 rounded-4">
                        Следующая →
                    </a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Вернуться к альбому -->
    <div class="text-center mt-3">
        <a href="{% url 'viapp:album' photo.album_id %}" class="btn btn-secondary">
            Вернуться к альбому
        </a>
    </div>
</div>
{% endblock %}

{% block extra_css %}

{% endblock %}

templates/viapp/share_album.html
{% extends "viapp/base.html" %}

{% block content %}
  <h2>Поделиться альбомом: {{ album.title }}</h2>
  <form method="post">
    {% csrf_token %}
    <p>Выберите пользователей:</p>
    {% for user in users %}
      <label>
        <input type="checkbox" name="users" value="{{ user.id }}"
               {% if user in album.shared_with.all %}checked{% endif %}>
        {{ user.username }}
      </label><br>
    {% endfor %}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

templates/viapp/signup.html
<!-- templates/signup.html -->
{% extends 'viapp/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}