users/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

viapp/urls.py
# адреса для страниц приложения viapp

from django.urls import path

from . import views

app_name = 'viapp'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница альбомов
    path('albums/', views.albums, name='albums'),
    # Страница альбома
    path('albums/<int:album_id>/', views.album, name='album'),
    # Страница фотографии
    path('album/<int:photo_id>/', views.photo, name='photo'),
    # Страница добавления альбома (для администратора)
    path('add_album/', views.add_album, name='add_album'),
    # Страница добавления фотографии (для администратора)
    path('add_photo/<int:album_id>/', views.add_photo, name='add_photo'),
    # Страница скачивания фотографий
    path('download_photo/<int:photo_id>/', views.download_photo, name = 'download_photo'),
    # Страница удаления фотографии (для администратора)
    path('delete_photo/<int:photo_id>/', views.delete_photo, name = 'delete_photo'),
    # Страница для скачивания альбома целиком
    path('download_album/<int:album_id>', views.download_album, name = 'download_album'),
    # Страница удаления альбома (для администратора)
    path('delete_album/<int:album_id>/', views.delete_album, name = 'delete_album'),
    # Страница удаления нескольких выбранных фотографий в альбоме (для администратора)
    path('delete_selected_photos/<int:album_id>/', views.delete_selected_photos, name = 'delete_selected_photos'),
    # Страница выбора обложки альбома (для администратора)
    path('select_cover/<int:album_id>/<int:photo_id>/', views.select_cover, name = 'select_cover'),
    # Страница перемещения расположения фотографии (для администратора)
    path('update_photo_order/', views.update_photo_order, name = 'update_photo_order'),
    # Страница для того, чтобы делиться правом просмотра альбома
    path('albums/<int:album_id>/share/', views.share_album, name='share_album'),
]

vitochka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name = 'index'),
    path('', include('viapp.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
{% extends 'viapp/base.html' %}

{% block title %}Домашняя страница{% endblock %}

{% block content %}

<style>

    /* Устанавливаем фон всей страницы */
  body {
        background: url('/static/images/background.jpg') no-repeat center center fixed;
        background-size: cover;
        font-family: 'Roboto', sans-serif; /* Изменение шрифта */
  }

  .col {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
  }

</style>

<div class ="container-fluid my-5 text-center">
  <div class ="row m-2 p-4">
  </div>
  <div class ="row m-2 p-2">
    <div class = "col-auto m-2 md-auto">
    </div>
    <!-- 1 ячейка -->
    <div class = "col-auto m-2">
      <!-- 1 блок -->
      <div class="user-features px-3 py-5">
        <h1 class="display-4 fw-bold">Добро пожаловать!</h1>
        <p class="fs-4">Ваш фотоархив всегда под рукой</p>
        <a href="{% url 'viapp:albums' %}" class="btn btn-primary btn-lg mt-3">
        Перейти к альбомам
        </a>
      </div>
    </div>
    <div class = "col-3 m-2">
    </div>
    <div class="col m-2">

      {% if user.is_authenticated %}
        
        <div class = "row m-2">
          <!-- Второй блок -->

          <div class="user-greeting mb-4 p-4 ms-lg-n3"
             style="background-color: rgba(255, 255, 255, 0); border-radius: 10px;">
            <h2>Привет, {{ user.username }}!</h2>
            <p>Рады снова видеть вас в системе</p>
            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">
              Выйти из системы
            </a>
          </div>
        </div>

        <div class = "row m-2">
          <!-- Третий блок -->
          <div class="user-features p-4"
               style="background-color: rgba(0, 0, 0, 0); color: black; border-radius: 10px;">
            <h2>Ваши возможности</h2>
            <ul class="list-unstyled">
              {% if not request.user.is_superuser %}
                <li>📸 Просматривайте понравившиеся вам фотографии и сохраняйте их</li>
              {% endif %}
              {% if request.user.is_superuser %}
                <li>📁 Создавайте альбомы</li>
                <li>📸 Загружайте фотографии</li>
                <li>🔒 Контролируйте доступ</li>
              {% endif %}
            </ul>
          </div>
        </div>
      
      {% else %}
        <!-- Блок для неавторизованных -->
        <div class="auth-box p-4 h-100"
             style="background-color: rgba(255, 255, 255, 0.9); border-radius: 10px;">
          <h2 class="mb-4">Начните работу</h2>
          <p class="lead mb-4">Авторизуйтесь для доступа ко всем функциям</p>
          <div class="d-grid gap-2 d-md-block">
            <a href="{% url 'login' %}" class="btn btn-primary btn-lg px-4 me-md-2">
              Войти
            </a>
            <a href="{% url 'signup' %}" class="btn btn-outline-secondary btn-lg px-4">
              Регистрация
            </a>
          </div>
        </div>
      {% endif %}

    </div>
  </div>

</div>



{% endblock %}